<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Blog extends CI_Controller {
    public function index()
    {
        $posts = [
            [
                'title' => "Our strength, Your Business",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.'
            ],
            [
                'title' => "How's the Economy?",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.'
            ],
            [
                'title' => "Tasty Innovations",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.'
            ],
            [
                'title' => "Seasonal Flavours",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.'
            ],
            [
                'title' => "Sweet Ingredients",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.'
            ],
            [
                'title' => "Making The Perfect Scoop",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.'
            ],
        ];

        $data = ['posts' => $posts];
        $this->load->view('templates/header');
        $this->load->view('blog/index', $data);
        $this->load->view('templates/footer');
    }

    public function details($id = 0)
    {
        $posts = [
            [
                'title' => "Our strength, Your Business",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.',
                'content' => "Google has been investing in AI for many years and bringing its benefits to individuals, businesses and communities. Whether it's publishing state-of-the-art research, building helpful products or developing tools and resources that enable others, we're committed to making AI accessible to everyone."
            ],
            [
                'title' => "How's the Economy?",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.',
                'content' => "We're now at a pivotal moment in our AI journey. Breakthroughs in generative AI are fundamentally changing how people interact with technology — and at Google, we've been responsibly developing large language models so we can safely bring them to our products."
            ],
            [
                'title' => "Tasty Innovations",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.',
                'content' => "More than 3 billion people already benefit from AI-powered features in Google Workspace, whether it's using Smart Compose in Gmail or autogenerated summaries in Google Docs."
            ],
            [
                'title' => "Seasonal Flavours",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.',
                'content' => "We're excited by the potential of generative AI, and the opportunities it will unlock — from helping people express themselves creatively, to helping developers build brand new types of applications."
            ],
            [
                'title' => "Sweet Ingredients",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.',
                'content' => "Stay tuned for more to come in the weeks and months ahead as we roll out new experiences to testers in the coming weeks."
            ],
            [
                'title' => "Making The Perfect Scoop",
                'img' => base_url('assets/images/placeholder.svg'),
                'author' => 'Admin',
                'date' => 'October 10, 2022',
                'excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur.',
                'content' => "If you're a manager onboarding a new employee, Workspace saves you time and effort involved in writing that first welcome email."
            ],
        ];

        if (!isset($posts[$id])) {
            show_404();
            return;
        }

        $data = [
            'post' => $posts[$id],
            'popular' => array_slice($posts, 0, 3)
        ];

        $this->load->view('templates/header');
        $this->load->view('blog/details', $data);
        $this->load->view('templates/footer');
    }
}
